require'nvim-autopairs'.setup()
require'colorizer'.setup()
require('alpha').setup(require('alpha.themes.startify').config)
require'venv-selector'.setup()
require('neoscroll').setup({duration_multiplier = 0.3})

require('setup.neo-tree')
require('setup.notify')
require('setup.nvim-treesitter')
require('setup.cmp')
require('setup.navic')
require('setup.illuminate')
require('setup.lsp')
require('setup.gitsigns')
require('setup.lualine')
require('setup.telescope')
require('setup.bufferline')
require('setup.toggleterm')
require('setup.gruvbox')
require('setup.dap')
require('setup.ibl')
require('setup.lint')
require('setup.autochdir')

require'dapui'.setup()

