require'nvim-autopairs'.setup()
require'colorizer'.setup()
require('alpha').setup(require('alpha.themes.startify').config)

require('setup.notify')
require('setup.nvim-tree')
require('setup.toggleterm')
require('setup.nvim-treesitter')
require('setup.cmp')
require('setup.navic')
require('setup.illuminate')
require('setup.lsp')
require('setup.symbols-outline')
require('setup.gitsigns')
require('setup.lualine')
require('setup.telescope')
require('setup.bufferline')
require('setup.gruvbox')
require('setup.dap')
require('setup.ibl')
require('setup.lint')

require'dapui'.setup()

